import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  CUSTOM_ACTION_GRANTS,
  PERMISSION_MATRIX,
  REVOKED_PERMISSIONS,
  USER_READ_ACTIONS,
  USER_READ_EXCLUDED_ROLES,
  USER_UID,
} from "./index";

/**
 * Generates infra/diagnostics/prod-perm-diff.sql, a read-only query that
 * compares a live database's users-permissions rows with what this code's
 * bootstrap sync (syncRolePermissions in ./index.ts) converges to.
 *
 * The expected set mirrors the sync order: matrix grants and the user-read
 * grants are ensured, REVOKED_PERMISSIONS is deleted, then
 * CUSTOM_ACTION_GRANTS is ensured, so a pair that is both revoked and a
 * custom grant ends up present. The users-permissions plugin seeds its own
 * DEFAULT_PERMISSIONS only on the very first boot; those rows are listed
 * with source `plugin_default_first_boot` and are informational.
 *
 * The SQL is a file snapshot: after changing the permission constants or
 * upgrading Strapi, regenerate it with
 *   pnpm vitest run apps/cms/src/prod-perm-diff.test.ts -u
 * CI fails while the committed file is stale.
 */

type Row = { role: string; action: string; sources: Set<string> };

function pluginDefaultPermissions(): { role: string; action: string }[] {
  // Read the installed plugin's list rather than copying it, so a Strapi
  // upgrade that changes the first-boot defaults makes this test fail.
  const requireFromCms = createRequire(join(__dirname, "..", "package.json"));
  const pkg = requireFromCms.resolve("@strapi/plugin-users-permissions/package.json");
  const source = readFileSync(
    join(dirname(pkg), "dist", "server", "services", "users-permissions.js"),
    "utf8",
  );
  const start = source.indexOf("DEFAULT_PERMISSIONS = [");
  const end = source.indexOf("];", start);
  if (start < 0 || end < 0) throw new Error("users-permissions DEFAULT_PERMISSIONS not found");
  const block = source.slice(start, end);
  const pairs = [...block.matchAll(/action:\s*'([^']+)',\s*roleType:\s*'([^']+)'/g)];
  if (pairs.length === 0) throw new Error("users-permissions DEFAULT_PERMISSIONS is empty");
  return pairs.map(([, action, role]) => ({ role, action }));
}

function expectedRows(): Row[] {
  const rows = new Map<string, Row>();
  const add = (role: string, action: string, source: string) => {
    const key = `${role} ${action}`;
    const row = rows.get(key) ?? { role, action, sources: new Set<string>() };
    row.sources.add(source);
    rows.set(key, row);
  };
  const drop = (role: string, action: string) => rows.delete(`${role} ${action}`);

  for (const [role, matrix] of Object.entries(PERMISSION_MATRIX)) {
    for (const [uid, actions] of Object.entries(matrix)) {
      for (const action of actions ?? []) add(role, `${uid}.${action}`, "matrix");
    }
    if (!USER_READ_EXCLUDED_ROLES.includes(role)) {
      for (const action of USER_READ_ACTIONS) add(role, `${USER_UID}.${action}`, "user_read");
    }
  }
  for (const [role, actions] of Object.entries(REVOKED_PERMISSIONS)) {
    for (const action of actions) drop(role, action);
  }
  const allRoles = Object.keys(PERMISSION_MATRIX);
  for (const [action, grant] of Object.entries(CUSTOM_ACTION_GRANTS)) {
    for (const role of grant === "*" ? allRoles : grant) add(role, action, "custom");
  }
  for (const { role, action } of pluginDefaultPermissions()) {
    add(role, action, "plugin_default_first_boot");
  }
  return [...rows.values()].sort(
    (a, b) => a.role.localeCompare(b.role) || a.action.localeCompare(b.action),
  );
}

const sqlString = (value: string) => `'${value.replace(/'/g, "''")}'`;

function buildSql(): string {
  const expected = expectedRows();
  const revoked = Object.entries(REVOKED_PERMISSIONS)
    .flatMap(([role, actions]) => actions.map((action) => ({ role, action })))
    .sort((a, b) => a.role.localeCompare(b.role) || a.action.localeCompare(b.action));
  const knownRoles = [...new Set([...Object.keys(PERMISSION_MATRIX), "authenticated", "public"])];

  const expectedValues = expected
    .map(
      (r) =>
        `  (${sqlString(r.role)}, ${sqlString(r.action)}, ${sqlString([...r.sources].sort().join("+"))})`,
    )
    .join(",\n");
  const revokedValues = revoked
    .map((r) => `  (${sqlString(r.role)}, ${sqlString(r.action)})`)
    .join(",\n");

  return `-- GENERATED by apps/cms/src/prod-perm-diff.test.ts from apps/cms/src/index.ts
-- (PERMISSION_MATRIX, user-read grants, REVOKED_PERMISSIONS, CUSTOM_ACTION_GRANTS)
-- and the installed users-permissions plugin's first-boot DEFAULT_PERMISSIONS.
-- Do not edit by hand; regenerate with:
--   pnpm vitest run apps/cms/src/prod-perm-diff.test.ts -u
--
-- READ-ONLY comparison of the live users-permissions rows with what the code's
-- bootstrap sync converges to. Run on the host:
--   docker exec -i infra-db-1 sh -c 'psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB"' < infra/diagnostics/prod-perm-diff.sql
--
-- Result kinds:
--   EXTRA_IN_DB    granted in the DB but not by the code (admin-panel edits, leftovers);
--                  revoked_by_code = true means the next boot's sync deletes it
--   MISSING_IN_DB  expected by the code but absent; rows whose source is only
--                  plugin_default_first_boot are informational (seeded on the first boot only)
--   DUPLICATE      the same (role, action) linked more than once
\\pset pager off
BEGIN TRANSACTION READ ONLY;
SET LOCAL statement_timeout = '30s';

\\echo '== 1. permission rows: code vs database'
WITH expected(role_type, action, source) AS (VALUES
${expectedValues}
),
revoked(role_type, action) AS (VALUES
${revokedValues}
),
actual AS (
  SELECT r.type AS role_type, p.action, count(*) AS n
  FROM up_permissions p
  JOIN up_permissions_role_lnk l ON l.permission_id = p.id
  JOIN up_roles r ON r.id = l.role_id
  GROUP BY r.type, p.action
)
SELECT CASE WHEN e.action IS NULL THEN 'EXTRA_IN_DB'
            WHEN a.action IS NULL THEN 'MISSING_IN_DB'
            ELSE 'DUPLICATE' END AS kind,
       coalesce(a.role_type, e.role_type) AS role_type,
       coalesce(a.action, e.action) AS action,
       e.source,
       (rv.action IS NOT NULL) AS revoked_by_code,
       a.n
FROM actual a
FULL OUTER JOIN expected e ON e.role_type = a.role_type AND e.action = a.action
LEFT JOIN revoked rv ON rv.role_type = coalesce(a.role_type, e.role_type)
                    AND rv.action = coalesce(a.action, e.action)
WHERE e.action IS NULL OR a.action IS NULL OR a.n > 1
ORDER BY 1, 2, 3;

\\echo '== 2. roles the code does not know'
SELECT r.id, r.type, r.name, count(l.permission_id) AS grants,
       (SELECT count(*) FROM up_users_role_lnk ul WHERE ul.role_id = r.id) AS users
FROM up_roles r LEFT JOIN up_permissions_role_lnk l ON l.role_id = r.id
WHERE r.type NOT IN (${knownRoles.map(sqlString).join(", ")})
GROUP BY r.id, r.type, r.name ORDER BY r.type;

\\echo '== 3. orphaned permission rows and links'
SELECT 'PERM_WITHOUT_ROLE' AS kind, p.id, p.action FROM up_permissions p
  LEFT JOIN up_permissions_role_lnk l ON l.permission_id = p.id WHERE l.permission_id IS NULL
UNION ALL
SELECT 'LINK_WITHOUT_PERM', l.permission_id, NULL FROM up_permissions_role_lnk l
  LEFT JOIN up_permissions p ON p.id = l.permission_id WHERE p.id IS NULL
ORDER BY 1, 2;

ROLLBACK;
`;
}

describe("infra/diagnostics/prod-perm-diff.sql", () => {
  it("matches the permission constants and plugin defaults it is generated from", async () => {
    await expect(buildSql()).toMatchFileSnapshot("../../../infra/diagnostics/prod-perm-diff.sql");
  });

  it("never lists a revoked pair as expected unless a custom grant re-adds it", () => {
    const expected = new Set(expectedRows().map((r) => `${r.role} ${r.action}`));
    for (const [role, actions] of Object.entries(REVOKED_PERMISSIONS)) {
      for (const action of actions) {
        const regranted =
          CUSTOM_ACTION_GRANTS[action] === "*"
            ? role in PERMISSION_MATRIX
            : (CUSTOM_ACTION_GRANTS[action] ?? []).includes(role);
        expect(expected.has(`${role} ${action}`)).toBe(regranted);
      }
    }
  });
});
